# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn test
    - name: Ls
      run:
        ls -la *
    - name: Realization
      run: echo -e "Identified risks\nFunctional specifications\nTechnical specifications" >> realization.txt
    - name: cat Realization
      run: cat realization.txt
    - name: JD&TODO generation 
      run: java -jar JDGenerator-jar-with-dependencies.jar texte/fig3.jd -o output/fig3.jd -svg -svgR -td -rea realization.txt   
    - name: Archive JD&TODO
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: output/
    - name: Archive realization.txt
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: realization.txt
    
