# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test with Maven
      run: mvn test
    - name: set Variable
      run: |
        echo -e "justification/output/" >> varOutput.txt
        echo -e "justification/" >> varInput.txt
        echo -e "false" >> DoIGenerate.txt
    - name: Realization part1
      run: echo -e "JUnit test\nBuild Maven\nJacoco Report" >> realization.txt
    - name: Realization part2
      run: echo -e "Jacoco Report Archivate!-!target/site/jacoco" >> realization.txt
    - name: JD&TODO generation 
      env: isTrue = $(cat DoIGenerate.txt)
      if: "$isTrue" == true
      run: java -jar JDGenerator-jar-with-dependencies.jar $(cat varInput.txt)basic.jd -o $(cat varOutput.txt)basic -svg -svgR -td realization.txt -rea
    - name: Archive JD&TODO
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: justification/output/
    - name: Archive realization.txt
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: realization.txt
    - name: Archive Jacoco report
      uses: actions/upload-artifact@v2
      with: 
        name: jacoco
        path: target/site/jacoco
    - name: memorise the final result
      env: isTrue = $(cat DoIGenerate.txt)
      if: "$isTrue" == true
      run: 
       git config user.name "GitHub Actions";
       git status; 
       echo -e "--------------";
       git add $(cat varOutput.txt)*;
       git commit -m "add output";
       git status;
       echo -e "--------------";
       git push -v;
       echo -e "--------------";
