# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Ls 1
      run:
        ls -la *
    - name: Realization
      run: echo -e "Identified risks\nFunctional specifications\nRisk mitigation plan" >> realization.txt
    - name: JD&TODO generation 
      run: java -jar JDGenerator-jar-with-dependencies.jar justification/fig3.jd -o output/fig3 -svg -svgR -td realization.txt -rea
    - name: Ls 2
      run:
        ls -la *
    - name: Archive JD&TODO
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: output/
    - name: Archive realization.txt
      uses: actions/upload-artifact@v2
      with: 
        name: GeneratedJD
        path: realization.txt
    - name: memorise the final result
      run: 
       git config user.name "GitHub Actions";
       git status; 
       echo -e "--------------";
       git add output/*;
       git commit -m "add output";
       git status;
       echo -e "--------------";
       git push -v;
       echo -e "--------------";
